services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\NewsImporticsxml\:
    resource: '../Classes/*'

  GeorgRinger\NewsImporticsxml\Command\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'news:importicsxml'

  GeorgRinger\NewsImporticsxml\EventListener\NewsImportListener:
    tags:
      - name: event.listener
        identifier: 'newsimporticsxml-newsimportlistener'
        event: GeorgRinger\News\Event\NewsImportPostHydrateEvent
